swagger: '2.0'
info:
  description: >-
    Defines the API available for hrv-social users to interact with groups,
    users and messages
  version: 1.0.0
  title: hrv-social
  contact:
    email: admin-list@example.com
host: <hostname>.execute-api.<region>.amazonaws.com
basePath: /Test
schemes:
  - https
tags:
  - name: groups
    description: Everything about groups
  - name: users
    description: Everything about users
consumes:
  - application/json
produces:
  - application/json
paths:
  /group/members:
    get:
      tags:
        - groups
      summary: Get all of the members of the group the caller belongs to
      description: ''
      operationId: getGroupMembers
      responses:
        '200':
          description: Expected response
          schema:
            $ref: '#/definitions/UserList'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
  /group/messages:
    get:
      tags:
        - groups
      summary: Get all of the messages for the group the caller belongs to
      description: ''
      operationId: getGroupMessages
      responses:
        '200':
          description: Expected response
          schema:
            $ref: '#/definitions/GroupMessageList'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
    post:
      tags:
        - groups
      summary: Create a new message for the group the caller belongs to
      description: ''
      operationId: createGroupMessage
      parameters:
        - in: body
          name: message
          description: The message to send to the group
          schema:
            $ref: '#/definitions/GroupMessage'
      responses:
        '201':
          description: Created successfully
          schema:
            $ref: '#/definitions/GroupMessage'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '201'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
  '/users/{user_id}':
    get:
      tags:
        - users
      summary: Get the details for a given user
      description: ''
      operationId: getUser
      parameters:
        - in: path
          name: user_id
          type: string
          required: true
          description: id of the user to fetch
      responses:
        '200':
          description: Expected response
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
  '/users/messages/{user_id}':
    get:
      tags:
        - users
      summary: Get the messages between the user making the call and user_id
      description: ''
      operationId: getUserMessages
      parameters:
        - in: path
          name: user_id
          type: string
          description: >-
            The id of the user whose correspondence with the caller should be
            fetched
          required: true
      responses:
        '200':
          description: Expected response
          schema:
            $ref: '#/definitions/UserMessageList'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
    post:
      summary: Send a message from the user making the call to another user
      tags:
        - users
      description: ''
      operationId: createUserMessage
      parameters:
        - in: path
          name: user_id
          description: The id of the message recipient
          type: string
          required: true
        - in: body
          name: message
          description: The message to send to the user
          required: true
          schema:
            $ref: '#/definitions/UserMessage'
      responses:
        '201':
          description: Created successfully
          schema:
            $ref: '#/definitions/GroupMessage'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '201'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
  '/users/roles':
    get:
      tags:
        - users
      summary: Returns a list of the security roles the calling user holds.
      description: >-
        The list may be empty if the user is not assigned any particular roles.
        Note that these are not necessarily AWS IAM roles - they might be Cognito user pool groups or anything
        else the implementation defines.
      operationId: getUserRoles
      responses:
        '200':
          description: Expected response
          schema:
            $ref: '#/definitions/UserRoleList'
        '400':
          description: Bad request error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      security:
        - basic-user: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: >-
          arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<account_id>:function:<function_name>/invocations
        credentials: 'arn:aws:iam::<account_id>:role/api-gateway-lambda-and-logs'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
securityDefinitions:
  basic-user:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: cognito_user_pools
    x-amazon-apigateway-authorizer:
      providerARNs:
        - 'arn:aws:cognito-idp:<region>:<account_id>:userpool/<pool_id>'
      type: cognito_user_pools
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    required:
      - message
  GroupMessage:
    type: object
    properties:
      id:
        type: string
      group_id:
        type: string
      date:
        type: string
        format: date-time
      from_id:
        type: string
        description: id of the user who sent the message
      body:
        type: string
    required:
      - body
  GroupMessageList:
    type: array
    items:
      $ref: '#/definitions/GroupMessage'
  User:
    type: object
    properties:
      id:
        type: string
      group:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
        description: "If this is empty or not provided, phone must be set."
      phone:
        type: string
        description: "If this is empty or not provided, email must be set."
      photoUrl:
        type: string
    required:
      - id
      - group
      - first_name
      - last_name
      - photoUrl
  UserList:
    type: array
    items:
      $ref: '#/definitions/User'
  UserMessage:
    type: object
    properties:
      id:
        type: string
      to_id:
        type: string
        description: id of the message recipient
      date:
        type: string
        format: date-time
      from_id:
        type: string
        description: id of the user who sent the message
      body:
        type: string
    required:
      - to_id
      - body
  UserMessageList:
    type: array
    items:
      $ref: '#/definitions/UserMessage'
  UserRoleList:
    type: array
    items:
      type: string
