AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to remind study participants to do daily training

Parameters:
  DynamoDBEndpoint:
    Type: String
    Description: overrides DynamoDB endpoint URL
  EmailTemplate:
    Type: String
    Description: The template to use when sending email
  TargetMinutesByWeek:
    Type: String
    Description: JSON array of numbers representing target minutes of training each week (array[0] == week1, etc.)

Resources:
  GroupsTable:
    Type: "AWS::Serverless::SimpleTable"
  UsersTable:
    Type: "AWS::Serverless::SimpleTable"
  UserDataTable:
    Type: "AWS::Serverless::SimpleTable"
  Remind:
    Type: AWS::Serverless::Function
    Properties:
      Handler: remind.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 5000
      Environment:
        Variables:
          DYNAMO_ENDPOINT: !Ref DynamoDBEndpoint
          GROUPS_TABLE: !Ref GroupsTable
          USERS_TABLE:  !Ref UsersTable
          USER_DATA_TABLE: !Ref UserDataTable
          EMAIL_TEMPLATE: !Ref EmailTemplate
          TARGET_MINUTES_BY_WEEK: !Ref TargetMinutesByWeek
